[package]
name = "tetra_ldtk"
version = "0.1.0"
authors = ["fighterwing989 <fighterwing89@gmail.com>"]
edition = "2018"

[dependencies]
tetra = "0.6.*"
serde = { version ="1.*", features=["derive"] }
serde_json = "1.*"